# Generated by Django 2.2.5 on 2020-01-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=3)),
                ('semester', models.IntegerField()),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('image', models.ImageField(height_field='500', upload_to='image/%Y/%m/%d/', width_field='500')),
            ],
        ),
    ]
