# Generated by Django 2.2.1 on 2020-01-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200121_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='home/static/image/%Y/%m/%d/'),
        ),
    ]
