# Generated by Django 2.2.1 on 2020-01-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200124_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='home/static/image/%Y'),
        ),
    ]
