# Generated by Django 2.2.5 on 2020-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200126_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
