# Generated by Django 3.0.6 on 2020-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_facultyadvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyadvisor',
            name='branch',
            field=models.CharField(default='IT', max_length=3),
            preserve_default=False,
        ),
    ]
