# Generated by Django 2.2.5 on 2020-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=4)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('lecture', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('roll_number', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=1)),
                ('prof_username', models.CharField(max_length=40)),
                ('lecture', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('date', 'time', 'roll_number')},
            },
        ),
    ]
