# Generated by Django 2.2.1 on 2020-01-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_username', models.CharField(max_length=40)),
                ('time', models.TimeField()),
                ('day', models.CharField(default='sunday', max_length=10)),
                ('class_name', models.CharField(max_length=10)),
                ('lecture', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='date',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(default='sunday', max_length=10),
        ),
    ]
