# Generated by Django 2.2.1 on 2020-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200125_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professortimetable',
            name='time',
        ),
        migrations.AddField(
            model_name='professortimetable',
            name='end_time',
            field=models.TimeField(default='18:05:00'),
        ),
        migrations.AddField(
            model_name='professortimetable',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
