# Generated by Django 2.2.1 on 2020-01-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200125_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(default='09:50:00'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'start_time', 'end_time', 'roll_number')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
