# Generated by Django 2.2.5 on 2020-01-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200126_0620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
    ]
