# Generated by Django 2.2.5 on 2020-01-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200126_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture_type',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
