# Generated by Django 2.2.5 on 2020-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_attendance_lecture_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('lecture', models.CharField(max_length=40)),
                ('lecture_type', models.CharField(max_length=2)),
            ],
        ),
    ]
